In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
from keras.layers import Layer
#All variables/parameters must be tensorflow variable as we need to feed them inside the computation graph and tell whether it has to be trained or not

In [29]:
class lcombination_Layer(Layer):
  def __init__(self,units=3):
    super(lcombination_Layer,self).__init__()
    self.units=units
  
  def build(self,input_shape):
    # input_shape=input.shape[0]
    wts_init=tf.random_normal_initializer()

    self.wts=tf.Variable(initial_value=wts_init(shape=(input_shape[-1],self.units)),
                         trainable=True,dtype='float32'
                         )
    self.bias=tf.Variable(initial_value=tf.zeros_initializer()(shape=(self.units,)),
                          trainable=True,dtype='float32'
                          )
  
  def call(self,input):
    ans=tf.matmul(input,self.wts)+self.bias
    return ans

ll=lcombination_Layer(20)

ll(tf.ones((2, 2)))
ll.weights


[<tf.Variable 'lcombination__layer_4/Variable:0' shape=(2, 20) dtype=float32, numpy=
 array([[ 0.03021215,  0.0931913 ,  0.01853705, -0.00551992, -0.0606694 ,
         -0.02736589, -0.04462356,  0.00421912,  0.07916684,  0.02666534,
         -0.00579744,  0.01617802,  0.01010777, -0.00479433,  0.04455417,
          0.11207785, -0.01171782,  0.01052913,  0.02092612,  0.0542494 ],
        [-0.05577335,  0.08635243,  0.02126202, -0.02540554, -0.03068448,
         -0.04295112,  0.04693201, -0.00997294, -0.02374625, -0.0338445 ,
         -0.03867098, -0.03922579, -0.02319262,  0.02063885,  0.04058544,
         -0.05983225,  0.01872281, -0.00215535,  0.00698939,  0.0730015 ]],
       dtype=float32)>,
 <tf.Variable 'lcombination__layer_4/Variable:0' shape=(20,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.], dtype=float32)>]

# Rough WORK

In [9]:
rni=tf.random_normal_initializer()
rni(shape=(1,3))#__call__ based

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.01288616,  0.02024633,  0.10976233]], dtype=float32)>